/*
 *  Copyright (c) 2023, WSO2 LLC. (http://www.wso2.org) All Rights Reserved.
 *
 *  WSO2 Inc. licenses this file to you under the Apache License,
 *  Version 2.0 (the "License"); you may not use this file except
 *  in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */

package io.ballerina.graphql.generator.gateway;

import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * Class to test gateway generated by sending requests to the gateway.
 */
public class GatewayExecutionTest {
    private static final String GATEWAY_URL = "http://localhost:9000";
    private static final String ASTRONAUT_SUBGRAPH_URL = "http://localhost:5001";
    private static final String MISSION_SUBGRAPH_URL = "http://localhost:5002";

    private static final Path supergraphSdl =
            Paths.get("src/test/resources/federationGateway/supergraphSchemas/Supergraph.graphql");
    private static final Path services = Paths.get("src/test/resources/federationGateway/subgraphServices");

    private Path tmpDir;
    Process astronautServiceProcess;
    Process missionsServiceProcess;
    Process gatewayProcess;

    @BeforeSuite
    public void setup() throws IOException {
        this.tmpDir = Files.createTempDirectory("graphql-gateway-" + System.nanoTime());
        File gatewayExec = TestUtils.generateGatewayJar(supergraphSdl, tmpDir);
        gatewayProcess = new ProcessBuilder("java", "-jar", gatewayExec.getAbsolutePath()).start();

        astronautServiceProcess = new ProcessBuilder("java", "-jar",
                TestUtils.getBallerinaExecutableJar(
                                services.resolve("astronautService").toAbsolutePath(), tmpDir)
                        .getAbsolutePath()).start();
        missionsServiceProcess = new ProcessBuilder("java", "-jar",
                TestUtils.getBallerinaExecutableJar(
                                services.resolve("missionsService").toAbsolutePath(), tmpDir)
                        .getAbsolutePath()).start();

        TestUtils.waitTillUrlIsAvailable(gatewayProcess, ASTRONAUT_SUBGRAPH_URL);
        TestUtils.waitTillUrlIsAvailable(astronautServiceProcess, MISSION_SUBGRAPH_URL);
        TestUtils.waitTillUrlIsAvailable(missionsServiceProcess, GATEWAY_URL);
    }

    @AfterSuite
    public void cleanup() throws IOException {
        astronautServiceProcess.destroy();
        missionsServiceProcess.destroy();
        gatewayProcess.destroy();
        TestUtils.deleteDirectory(tmpDir);
    }

    @Test(description = "Test gateway execution",
    dataProvider = "RequestResponseDataProvider")
    public void testGatewayExecution(String requestFile, String responseFile) throws IOException {
        String query = TestUtils.getRequestContent(requestFile);
        String expectedResponse = TestUtils.getResponseContent(responseFile);

        URL url = new URL(GATEWAY_URL);
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        connection.setRequestMethod("POST");
        connection.setRequestProperty("Content-Type", "application/json");
        connection.setDoOutput(true);
        byte[] body = ("{\"query\":\"{" + query + "}\"}").getBytes();
        connection.getOutputStream().write(body);

        // read and assert the response from the server
        BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()));
        StringBuilder response = new StringBuilder();
        String line;
        while ((line = in.readLine()) != null) {
            response.append(line);
        }
        in.close();
        Assert.assertEquals(response.toString(), expectedResponse);
    }

    @DataProvider(name = "RequestResponseDataProvider")
    public Object[][] getData(){
        return new Object[][]{
                {"request1", "response1"},
                {"request2", "response2"},
        };
    }

}
